### ISSUE TITLE
Option for local NTP server

### ISSUE THREAD

**Issue by andreapx** [info-beamer/package-magic-video-wall#1]
It would be nice to have the posasibility to set the IP of an NTP server so that an additional Raspberry can be setup to provide it in location where Internet is not available.
To bypass this problem right now, what is the DNS of the NTP server that you're using so that I can setup a DNS server and map the NTP server to my Raspberry?

**Comment by dividuum** [comment]
This already exists: You can set both DNS as well as NTP server in the device's configuration UI on each device's detail page:
![image](https://user-images.githubusercontent.com/214550/234932140-37e1a9bc-2a65-4c66-9c2d-974851bba29f.png)

**Comment by andreapx** [comment]
Oh, sorry, I've missed it.
Thanks!
